# Generated by Django 5.1.5 on 2026-05-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('browser', 'Browser (WebRTC / MediaRecorder dari client)'), ('local', 'Local device (cv2 di mesin Django)'), ('rtsp', 'RTSP / IP camera')], default='browser', max_length=16)),
                ('source_config', models.JSONField(blank=True, default=dict)),
                ('mode', models.CharField(choices=[('live_only', 'Live only (tidak merekam)'), ('cctv', 'CCTV (rekam segmen 30 menit)')], default='live_only', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='camera.camera')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['camera', '-started_at'], name='camera_reco_camera__6cb610_idx')],
            },
        ),
    ]
